### ISSUE TITLE
Add variable extract

### ISSUE THREAD

**Issue by iainsmith** [pashamur/ruby-extract-method#1]
Hi @pashamur, really glad I stumbled across this plugin today. Second thing I tried to do was extract a variable. Would love to see it added in the future.

**Comment by pashamur** [comment]
Hey @iainsmith - thanks for your feedback! I'll definitely take a look into it (probably over the weekend when I have a little more time).

**Comment by mhenrixon** [comment]
Not sure but you don't get a whole lot of weekends over a year? :)
